---
adapter:
  route: xs2a-adapter-dev.cloud.adorsys.de
  namespace: xs2a-adapter-dev
  tag: develop
  adapterConfigFile: config/xs2a-adapter-dev/adapter.config.properties
  graylogHost: xs2a-adapter-graylog-graylog
