---
adapter:
  route: xs2a-adapter-integ.cloud.adorsys.de
  namespace: xs2a-adapter-integ
  tag: develop
  aspspConfig: true
  aspspConfigFile: config/xs2a-adapter-integ/aspsp-adapter-config.csv
  adapterConfigFile: config/xs2a-adapter-integ/adapter.config.properties
  profiles: dev
  graylogHost: xs2a-adapter-graylog-graylog
