server:
  port: 8999

info:
  app:
    name: ${spring.application.name}
    description: @project.description@
    version: @project.version@
    build: '#@build.number@'
    artifactId: @project.artifactId@

spring:
  application:
    name: xs2a-adapter
  jackson:
    default-property-inclusion: non_null
    serialization:
      indent-output: true
      write-dates-as-timestamps: false
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false


aspsp-registry:
  support-multiple-records: true
---
spring:
  profiles: dev
logging:
  config: classpath:logback-dev.xml
  level:
    org.apache.http.wire: DEBUG
