server:
  port: 8999

info:
  app:
    name: ${spring.application.name}
    description: '@project.description@'
    version: @project.version@
    build: '#@build.number@'
    artifactId: @project.artifactId@

spring:
  application:
    name: xs2a-adapter
  jackson:
    default-property-inclusion: non_null
    serialization:
      indent-output: true
      write-dates-as-timestamps: false
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus

xs2a-adapter:
  rest:
    mime-headers-support-enabled: true
  loader:
    choose-first-from-multiple-aspsps: true

graylog:
  host: localhost
  port: 12201

audit:
  sanitized: true

---
spring:
  profiles: dev
logging:
  level:
    de.adorsys.xs2a.adapter.http.ApacheHttpClient: DEBUG
    de.adorsys.xs2a.adapter.http.ResponseHandlers: DEBUG
    de.adorsys.xs2a.adapter.registry.LuceneAspspRepository: DEBUG
    de.adorsys.xs2a.adapter.adapter.BaseOauth2Service: DEBUG
  pattern:
    level: "%5p %mdc{correlationId}"
