server:
  port: 8999

info:
  app:
    name: ${spring.application.name}
    description: "Description"
    version: @project.version@
    build: '#@build.number@'
    artifactId: @project.artifactId@

spring:
  application:
    name: xs2a-adapter
  jackson:
    default-property-inclusion: non_null

---
spring:
  profiles: dev
logging:
  config: classpath:logback-dev.xml
  level:
    org.apache.http.wire: DEBUG
