server:
  port: 8999

info:
  app:
    name: ${spring.application.name}
    description: '@project.description@'
    version: @project.version@
    build: '#@build.number@'
    artifactId: @project.artifactId@

spring:
  application:
    name: xs2a-adapter
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus

xs2a-adapter:
  rest:
    mime-headers-support-enabled: true
  loader:
    choose-first-from-multiple-aspsps: true
  audit:
    sanitized: true
  wire-mock:
    mode: true
    standalone:
      url: http://localhost:8008
    validation:
      enabled: false
  sanitizer:
    whitelist: recurringIndicator, validUntil, frequencyPerDay, combinedServiceIndicator

graylog:
  host: localhost
  port: 12201

---
spring:
  profiles: dev
logging:
  level:
    de.adorsys.xs2a.adapter.impl.http.ApacheHttpClient: DEBUG
    de.adorsys.xs2a.adapter.impl.http.ResponseHandlers: DEBUG
    de.adorsys.xs2a.adapter.registry.LuceneAspspRepository: DEBUG
    de.adorsys.xs2a.adapter.impl.BaseOauth2Service: DEBUG
  pattern:
    level: "%5p %mdc{correlationId}"
