apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: xs2a-adapter
  name: xs2a-adapter
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: xs2a-adapter
    deploymentconfig: xs2a-adapter
  template:
    metadata:
      {{- if .Values.logback.enabled }}
      annotations:
      checksum/config: {{ include (print $.Template.BasePath "/configmap-logback.yaml") . | sha256sum }}
      {{- end }}
      labels:
        app: xs2a-adapter
        deploymentconfig: xs2a-adapter
    spec:
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev,sandbox
            {{- if .Values.adapter.aspspConfig }}
            - name: csv.aspsp.adapter.config.file.path
              value: /opt/xs2a-adapter/custom-config/aspsp-adapter-config.csv
            {{- end }}
            {{- if .Values.logback.enabled }}
            - name: LOGGING_CONFIG
              value: /data/logback.xml
            {{- end }}
            - name: csv.aspsp.adapter.config.file.path
              value: /opt/xs2a-adapter/custom-config/adapter.config.properties
            - name: KEY_STORE_TYPE
              valueFrom:
                secretKeyRef:
                  name: qwac-secret
                  key: key-store-type
            - name: KEY_STORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: qwac-secret
                  key: key-store-password
            - name: JAVA_OPTS
              value: >-
                -Xmx1024m
                -Dcom.sun.security.enableAIAcaIssuers=true
                -Djavax.net.ssl.keyStoreType=$(KEY_STORE_TYPE)
                -Djavax.net.ssl.keyStore=/qwac/key-store
                -Djavax.net.ssl.keyStorePassword=$(KEY_STORE_PASSWORD)
                -Dpkcs12.keyStore=/pkcs12/key-store.p12
          imagePullPolicy: Always
          name: xs2a-adapter
          ports:
            - containerPort: 8081
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - name: qwac-secret-volume
              mountPath: /qwac
            - name: pkcs12-key-store-secret-volume
              mountPath: /pkcs12
            - name: xs2a-adapter-config
              mountPath: /opt/xs2a-adapter/custom-config
            {{- if .Values.logback.enabled }}
            - name: logging-config
              mountPath: /data/logback.xml
              subPath: logback.xml
            {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: qwac-secret-volume
          secret:
            secretName: qwac-secret
        - name: pkcs12-key-store-secret-volume
          secret:
            secretName: pkcs12-key-store-secret
        - name: xs2a-adapter-config
          persistentVolumeClaim:
            claimName: xs2a-adapter-config
        {{- if .Values.adapter.aspspConfig }}
        - configMap:
            defaultMode: 292
            name: xs2a-adapter-logging-config
          name: logging-config
        {{- end }}
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - xs2a-adapter
        from:
          kind: ImageStreamTag
          name: xs2a-adapter:{{ .Values.adapter.tag }}
          namespace: {{ .Values.adapter.namespace }}
      type: ImageChange
