name: Banking Gateway Dev CI
on:
  push:
    branches:
      - banking-gateway-extended-logging

env:
  XS2A_ADAPTER_IMAGE_NAME: xs2a-adapter
  XS2A_ADAPTER_IMAGE_TAG: latest
  OPENSHIFT_REGISTRY: openshift-registry.adorsys.de
  OPENSHIFT_NAMESPACE_BGW_DEV: banking-gateway-dev

jobs:
  build:
    name: Build project & docker file
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build project
        run: mvn clean verify -B

      - name: Build docker image
        env:
          LOCAL_IMAGE_NAME: ${{ env.XS2A_ADAPTER_IMAGE_NAME }}:test
        run: docker build -t ${LOCAL_IMAGE_NAME} .

  deploy:
    name: Deploy docker image to the registry
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Publish packages
        run: mvn -B deploy -Dmaven.test.skip=true -Dbuild.number=${GITHUB_SHA::7}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docker image
        env:
          LOCAL_IMAGE_NAME: ${{ env.XS2A_ADAPTER_IMAGE_NAME }}:${{ env.XS2A_ADAPTER_IMAGE_TAG }}
        run: docker build -t ${LOCAL_IMAGE_NAME} .

      - name: DEV. Docker login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.OPENSHIFT_REGISTRY }}
          username: image-pusher
          password: ${{ secrets.OPENSHIFT_TOKEN_BGW_DEV }}

      - name: BGW DEV. Deploy docker image
        env:
          LOCAL_IMAGE_NAME: ${{ env.XS2A_ADAPTER_IMAGE_NAME }}:${{ env.XS2A_ADAPTER_IMAGE_TAG }}
          OPENSHIFT_IMAGE_NAME: ${{ env.OPENSHIFT_REGISTRY }}/${{ env.OPENSHIFT_NAMESPACE_BGW_DEV }}/${{ env.XS2A_ADAPTER_IMAGE_NAME }}:${{ env.XS2A_ADAPTER_IMAGE_TAG }}
        run: |
          docker tag ${LOCAL_IMAGE_NAME} ${OPENSHIFT_IMAGE_NAME}
          docker push ${OPENSHIFT_IMAGE_NAME}

